### ISSUE TITLE
*nix-like behaviour when copying to a directory

### ISSUE THREAD

**Issue by matthew-matvei** [screendriver/cp-cli#2]
Looks like a nice, helpful little tool for compatibility. I can see it's a small wrapper and you're not going for anything complex.

One small feature I feel would be useful, though, is being able to specify a directory as the destination. In Linux-land, at least, doing this copies the source files, maintaining their names, into the destination directory. `cp-cli` currently just complains in that use case.

**Comment by screendriver** [comment]
Good idea. At the time of being written that little tool `fs-extra` didn't support that (respectively easily).

I will look into that 😉

**Comment by matthew-matvei** [comment]
If it doesn't, I believe `fs.lstatSync("path/to/dir").isDirectory()` should be able to do the trick.

**Comment by screendriver** [comment]
Sorry for the delay, I was really busy recently. I published `1.1.0` to [npm](https://www.npmjs.com/package/cp-cli) 😉

**Comment by matthew-matvei** [comment]
Sweet, thanks
