### ISSUE TITLE
Unable to copy directory content

### ISSUE THREAD

**Issue by groupsky** [screendriver/cp-cli#3]
Since 9ef3453 the command `cp-cli srcdir destdir` is copying `srcdir` directory as a subdirectory of `destdir`. Before the change this would result in copying the **content** of `srcdir` inside `destdir`.

I think an additional check if source is a directory is required on [line #24](https://github.com/screendriver/cp-cli/commit/9ef345394738f11d03c82cbdb530823cde900e41#diff-c15a43cef2bbf860f6a2792fd4bd285eR24)

**Comment by screendriver** [comment]
Hi @groupsky,

sorry for the delayed answer. I completely oversight that issue 😳 If you want you can submit a PR or if not I will look into that soon 😉

**Comment by screendriver** [comment]
@groupsky I added a [test](https://github.com/screendriver/cp-cli/blob/master/test/cp-cli.test.ts#L44) for that now and can't reproduce your issue 🤔 Could you help me out with reproducing it? Thanks.

**Comment by groupsky** [comment]
It seems this problem happens only when the target directory exists. In your test the `out` doesn't exists so it passes. If you add the following before running the copy, the test fails.

```javascript
  shell.mkdir('out')
```

**Comment by groupsky** [comment]
Works for me now. Thanks

**Comment by screendriver** [comment]
Great 🎉
