### ISSUE TITLE
does this support globbing?

### ISSUE THREAD

**Issue by AndyOGo** [screendriver/cp-cli#6]

**Comment by screendriver** [comment]
What do you exactly mean? `cp-cli myDir/**/*.txt dest/`?

**Comment by AndyOGo** [comment]
yes, globbing for source definitions

**Comment by screendriver** [comment]
Did you tried it out?

**Comment by AndyOGo** [comment]
Sorry. No what I actually meant, if it supports cross os source globbing.
Not globs interpreted by the used shell.

For this arguments would need to be escaped like `cp-cli 'myDir/**/*.txt' dest/`

**Comment by screendriver** [comment]
Any pull request would be welcome ☺️

**Comment by screendriver** [comment]
After looking around I found out that in the last couple of years a lot of new, and better, alternatives to `cp-cli` were created. So in favour of [cpy-cli](https://github.com/sindresorhus/cpy-cli), [ncp](https://github.com/AvianFlu/ncp) and [cpx](https://github.com/mysticatea/cpx) I will archive this repository.
