### ISSUE TITLE
Copying into a folder doesn't work without specifying a filename in destination

### ISSUE THREAD

**Issue by kayvanbree** [screendriver/cp-cli#62]
On Windows, the following command works:

```
cp-cli README.md dist/my-lib/README.md
```

But the following commands don't work:

```
cp-cli README.md dist/my-lib/
cp-cli README.md dist/my-lib
```

According the docs the first one (with the slash) should work, but instead it gives the following error:

```
{ [Error: EPERM: operation not permitted, unlink 'C:\Projects\my-project\dist\my-lib']
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path:
   'C:\\Projects\\my-project\\dist\\my-lib' }
```

I solved this by adding the filename, but wanted to let you know. I don't know if this is also a problem on Unix systems.

Great work on this library by the way! `cpx` didn't want to copy a folder with assets and it hadn't been released for 3 years, so it's nice to see a fresh new copy library.

**Comment by screendriver** [comment]
I created a test environment for Windows here 3ee0afa04553336fa4801636c00597ea44cb531d and try to reproduce and fix it ☺️

**Comment by screendriver** [comment]
After looking around I found out that in the last couple of years a lot of new, and better, alternatives to `cp-cli` were created. So in favour of [cpy-cli](https://github.com/sindresorhus/cpy-cli), [ncp](https://github.com/AvianFlu/ncp) and [cpx](https://github.com/mysticatea/cpx) I will archive this repository.
